import html
import os
import uuid
import time
from typing import Sequence

import streamlit as st
from neo4j import GraphDatabase
from langfuse import Langfuse, propagate_attributes
from langfuse.langchain import CallbackHandler
from langchain_core.messages import HumanMessage

# Import your compiled LangGraph workflow
from src.agent.graph import graph
from src.ui.copy import (
    FOOTER_PHASE,
    FOOTER_TEAM,
    PAGE_SUBTITLE,
    PAGE_TITLE,
    PHONE_BRAND,
    SUGGESTIONS,
    action_label,
    detect_language,
    form_label,
    reason_choices,
)
from src.ui.messages import ChatMessage, initial_messages, is_opening_only, sources_of
from src.ui.theme import (
    SCREEN_HEIGHT_PX,
    assistant_label,
    inject_theme,
    page_footer,
    page_header,
    phone_header,
    role_marker,
    scroll_to_question,
    status_stack,
    theme_slider,
    type_out,
)
from src.ui.turns import TurnProgress, followup_suggestions, is_definitive_answer

# ==========================================
# CONFIGURATION & LANGFUSE SETUP
# ==========================================
st.set_page_config(
    page_title="IA Pool Assistant V1",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# Deep Water (dark) / Sunlit Lagoon (light). Must run before any other widget:
# it reads the slider's session-state value and paints every surface below.
inject_theme()

# --- page copy -------------------------------------------------------------
# The page copy, the greeting and the openers live in `src/ui/copy.py`, which
# `preview_ui.py` imports from as well — one declaration, so the harness cannot
# drift from the app it is meant to mirror.

# Per-answer feedback (the two thumbs under an answer) is ON.
#
# This is a deliberate, temporary divergence from the design spec, which moved
# feedback to the end-of-chat survey in v0.3 (option-c-deep-water.html) and
# removed the per-answer thumbs — see Documentation/feedback-capture-divergence.md.
# The thumbs stay for the test phase because the end-of-chat survey does not
# exist yet, and a phase whose whole purpose is collecting signal cannot ship
# with no way to collect it.
#
# Set to False to match the spec: the widget and its Langfuse plumbing stay
# intact either way, and nothing else needs to change. When the survey lands,
# this flag and `render_answer_actions` are what comes out.
SHOW_PER_ANSWER_FEEDBACK = True

# The planner's step list and the per-agent success/error boxes used to render
# straight into the conversation. User testing called that the "code screen":
# internal agent names and a raw plan dump flashing where an answer should be.
# It is control data for us, so it now hides behind this flag, in a collapsed
# expander, and testers see the honest status lines instead. Everything it used
# to show is on the Langfuse trace either way.
SHOW_PIPELINE_DEBUG = False

# --- Score naming (kept in constants so score_id stays stable across reruns) ---
SCORE_FEEDBACK = "user_feedback"
SCORE_REASON = "feedback_reason"

# Name used for the root span. The trace inherits it, so the Langfuse console
# lists something meaningful instead of an autogenerated LangGraph label.
TRACE_NAME = "pool-chemistry-turn"

# The negative-feedback taxonomy now lives in `src/ui/copy.py` as REASON_ORDER
# (the stored values, frozen — renaming one splits a category's history) plus
# REASON_COPY (the display labels, EN/ES). `reason_choices(lang)` returns the
# `{label: stored value}` mapping the picker needs, so a label can never be
# paired with the wrong value.


@st.cache_resource
def get_langfuse():
    """
    Single cached Langfuse client. Instantiating Langfuse() on every Streamlit
    rerun would spawn a new background thread + queue each time.

    environment/release are set here so scores and traces coming from dev runs
    can be filtered out of the console without touching the score payload.
    """
    try:
        client = Langfuse(
            environment=os.getenv("APP_ENV", "development"),
            release=os.getenv("APP_RELEASE", "local"),
        )
        if not client.auth_check():
            return None
        return client
    except Exception:
        return None


lf = get_langfuse()
if lf is None:
    st.sidebar.warning("Langfuse credentials not found or invalid. Tracking disabled.")



# ==========================================
# IDEMPOTENT SCORING HELPERS
# ==========================================
def build_score_id(trace_id: str, score_name: str) -> str:
    """
    Deterministic score id. Langfuse upserts by score id, so re-sending the same
    id overwrites instead of appending. This is the actual idempotency guarantee:
    N clicks -> exactly 1 score row, and flipping the verdict mutates the value.
    """
    return f"{trace_id}-{score_name}"


def submit_feedback(
    trace_id: str,
    value: int,
    comment: str,
    reason: str | None = None,
    turn_index: int | None = None,
):
    """
    Sends (or overwrites) the feedback score for a given trace.
    value: 1 = thumbs up, 0 = thumbs down (data_type NUMERIC)

    score metadata carries the conversation coordinates, so a score row is
    traceable back to a specific turn even when queried through the scores API
    in isolation from its trace.
    """
    if lf is None:
        st.toast("Langfuse deshabilitado: el feedback no se registró.")
        return False

    score_metadata = {
        "thread_id": st.session_state.thread_id,
        "turn_index": turn_index,
        "source": "streamlit_ui",
        "submitted_at": time.time(),
    }

    try:
        lf.create_score(
            score_id=build_score_id(trace_id, SCORE_FEEDBACK),
            trace_id=trace_id,
            name=SCORE_FEEDBACK,
            value=value,
            data_type="NUMERIC",
            comment=comment,
            metadata=score_metadata,
        )

        if reason is not None:
            lf.create_score(
                score_id=build_score_id(trace_id, SCORE_REASON),
                trace_id=trace_id,
                name=SCORE_REASON,
                value=reason,
                data_type="CATEGORICAL",
                comment=comment,
                metadata=score_metadata,
            )

        # The v3 SDK batches in a background thread. A Streamlit rerun can end
        # the script before the batch ships, so flush explicitly.
        lf.flush()
        return True
    except Exception as e:
        st.error(f"No se pudo registrar el feedback: {e}")
        return False


# ==========================================
# NEO4J CONNECTION HANDLER
# ==========================================
@st.cache_resource
def get_neo4j_driver():
    uri = os.getenv("NEO4J_URI")
    user = os.getenv("NEO4J_USER")
    password = os.getenv("NEO4J_PASSWORD")
    if not uri:
        return None
    return GraphDatabase.driver(uri, auth=(user, password))


def check_and_handle_neo4j() -> tuple[bool, str]:
    """
    Checks Neo4j connectivity. Returns (online, message).

    The message is returned rather than rendered, so the caller can show it
    inside the phone screen. Rendering it here would paint a full-width alert
    above the page title and break the framed layout.

    Note: If using Neo4j Aura Free Tier, it pauses automatically.
    Standard Python drivers cannot "unpause" Aura. You must use the Aura API
    to programmatically resume it, or resume it via the Neo4j Console.
    """
    driver = get_neo4j_driver()
    if not driver:
        return False, "Neo4j environment variables are missing."

    try:
        driver.verify_connectivity()
        return True, ""
    except Exception as e:
        if "getaddrinfo failed" in str(e) or "Timeout" in str(e):
            return False, (
                "**Neo4j Database is currently unreachable or paused.**\n\n"
                "If you are using Neo4j Aura Free Tier, it may have been paused due to inactivity. "
                "Please log into the [Neo4j Aura Console](https://console.neo4j.io/) to resume your instance."
            )
        return False, f"Neo4j Connection Error: {e}"


# ==========================================
# SESSION STATE INITIALIZATION
# ==========================================
if "thread_id" not in st.session_state:
    st.session_state.thread_id = str(uuid.uuid4())
if "messages" not in st.session_state:
    st.session_state.messages = initial_messages()
# Which answers currently have their sources panel open, keyed by trace id.
# Purely presentational — nothing here is sent anywhere.
if "sources_open" not in st.session_state:
    st.session_state.sources_open = {}
if "feedback" not in st.session_state:
    # trace_id -> {"value": int, "reason": str|None, "awaiting_detail": bool}
    st.session_state.feedback = {}
if "turn_counter" not in st.session_state:
    # Monotonic per-session counter. len(messages) is NOT safe as a trace seed:
    # a turn that dies before appending its assistant message leaves the length
    # unchanged, and the next prompt would reuse the same deterministic id.
    st.session_state.turn_counter = 0
if "db_online" not in st.session_state:
    st.session_state.db_online, st.session_state.db_message = check_and_handle_neo4j()

# The diagnostics that used to occupy the sidebar (session id, interaction and
# score counts, graph status) are intentionally not displayed: they are control
# and tracking data for us, not for the user. Nothing is lost — thread_id ships
# to Langfuse as both user_id and session_id, turn_index rides on every trace
# and score, and each score carries the same coordinates in its metadata.


# ==========================================
# PIPELINE DEBUG PANEL (opt-in)
# ==========================================
# Defined up here, not beside `run_turn` below, because the history loop calls it
# and that loop runs before `run_turn`'s own definition is reached.
def render_debug(lines: list[tuple[str, str]]) -> None:
    """
    The old in-conversation telemetry — the planner's step list and the
    per-agent success/error boxes — behind `SHOW_PIPELINE_DEBUG`, collapsed.

    Called from the history loop rather than from inside the turn, for the same
    reason the feedback widget is (FRONTEND.md §11.9): the turn ends in
    `st.rerun()`, so anything rendered during it is discarded a moment later.
    Rendered here it survives, and it stays out of the way of the answer.
    """
    if not (SHOW_PIPELINE_DEBUG and lines):
        return
    with st.expander("Details", expanded=False):
        for kind, text in lines:
            if kind == "error":
                st.error(text)
            elif kind == "info":
                st.info(text)
            else:
                st.markdown(text)


# ==========================================
# HELPER
# ==========================================
def _chip_texts(raw) -> list[str]:
    """
    `list[Suggestion]` → `list[str]`, que es lo que `render_suggestions` toma.

    Defensivo con el nombre del campo: el modelo puede exponer el texto como
    .label o .text, y un checkpoint viejo puede traer dicts en vez de objetos.
    Un chip vacío se descarta en vez de renderizar un botón sin texto.
    """
    out: list[str] = []
    for s in raw or []:
        if isinstance(s, str):
            text = s
        elif isinstance(s, dict):
            text = s.get("label") or s.get("text") or ""
        else:
            text = getattr(s, "label", None) or getattr(s, "text", "") or ""
        text = str(text).strip()
        if text:
            out.append(text)
    return out
# ==========================================
# OPENING SUGGESTIONS
# ==========================================
def render_suggestions(
    options: Sequence[str],
    disabled: bool = False,
    namespace: str = "pa-chips",
) -> None:
    """
    The openers under the greeting, and the same deck under the latest answer.
    A click stashes the text and reruns; the composer picks it up below and the
    turn runs exactly as if it were typed — so they follow the composer and go
    dead while the graph is unreachable.

    `namespace` keys both the container and its buttons. The two placements are
    mutually exclusive today, but they are one Streamlit rerun apart and a
    duplicate widget key raises rather than degrading, so they do not share one.
    The stylesheet matches `[class*="st-key-pa-chips"]`, which covers both.
    """
    with st.container(key=namespace):
        for i, text in enumerate(options):
            if st.button(text, key=f"sug_{namespace}_{i}", disabled=disabled):
                st.session_state.pending_prompt = text
                st.rerun()


# ==========================================
# FEEDBACK WIDGET
# ==========================================
# The trace id is deliberately not surfaced here. It still rides on every
# message dict and on every score sent to Langfuse — it is tracking data for
# us, so it belongs in the console, not on the user's screen.


def _submit_and_store(
    trace_id: str,
    value: int,
    turn_index: int | None,
    lang: str,
) -> None:
    """
    One thumb click: persist the score, remember it locally, repaint.

    The negative case stores the 0 immediately rather than waiting for the
    detail form to be completed — if the reader walks away we still keep the
    signal, and `score_id` is deterministic so finishing the form upserts the
    same row instead of adding a second one.

    `note` is the comment stored on the score, not something the reader sees, so
    it stays in one language: it is queried out of the Langfuse console and a
    comment that changed language per turn would be harder to filter, not
    easier. Only the toast follows the reader.
    """
    note = "Respuesta útil" if value == 1 else "Respuesta no útil (pendiente de detalle)"

    # The verdict is stored *before* the score is sent, and regardless of whether
    # sending works. Gating it on the send made the control's appearance depend on
    # telemetry: with no Langfuse client `submit_feedback` returns False, so the
    # thumb stayed unselected and the tap read as a dead button. Whether the score
    # reached Langfuse is a telemetry outcome; whether the reader's tap registered
    # is not, and the two do not belong on the same conditional.
    st.session_state.feedback[trace_id] = {
        "value": value,
        "reason": None,
        "awaiting_detail": value == 0,
    }

    # `submit_feedback` raises its own toast when it cannot record, so the thanks
    # is only shown when there is something to be thankful for — two contradicting
    # toasts would be worse than none.
    if submit_feedback(trace_id, value, note, turn_index=turn_index):
        st.toast(form_label(lang, "thanks_verdict"))
    st.rerun()


def _clear_verdict(trace_id: str) -> None:
    """
    Second tap on the already-chosen thumb: undo the selection.

    Only the local verdict is dropped, which is what returns the button to
    "secondary" and its unselected colour. It also takes `awaiting_detail` with
    it, so an open thumbs-down form closes rather than being left orphaned.

    The score already sent to Langfuse under the deterministic `score_id` is
    deliberately left in place: removing it is a telemetry decision, not a UI
    one. A later click on either thumb upserts that same row as before.
    """
    st.session_state.feedback.pop(trace_id, None)
    st.rerun()


def render_sources(msg: ChatMessage, trace_id: str, lang: str) -> None:
    """
    The panel the "View sources" menu item opens, under the answer it belongs to.

    It reports what the turn actually carries. Nothing populates
    `AgentResult.sources` today, so in practice this says the answer was not
    linked to a document — which is the honest statement, and the same reason
    the status line stopped naming a manual section (§8.2). The moment the
    backend starts returning sources, they appear here with no change.
    """
    if not st.session_state.sources_open.get(trace_id):
        return

    with st.container(key=f"pa-sources-{trace_id}"):
        st.markdown(
            f'<div class="pa-src-title">'
            f'{html.escape(action_label(lang, "sources_title"))}</div>',
            unsafe_allow_html=True,
        )
        sources = sources_of(msg)
        if sources:
            st.markdown(
                "".join(
                    '<div class="pa-src-item"><span>·</span>'
                    f"<span>{html.escape(src)}</span></div>"
                    for src in sources
                ),
                unsafe_allow_html=True,
            )
        else:
            st.markdown(
                f'<div class="pa-src-empty">'
                f'{html.escape(action_label(lang, "sources_empty"))}</div>',
                unsafe_allow_html=True,
            )
        if st.button(action_label(lang, "hide"), key=f"hidesrc_{trace_id}"):
            st.session_state.sources_open[trace_id] = False
            st.rerun()


def render_feedback_detail(trace_id: str, turn_index: int | None, lang: str) -> None:
    """
    The follow-up a thumbs-down opens: a category and an optional note.

    Two kinds of string meet in here and are kept apart deliberately:

      * what the reader sees — the prompt, the field labels, the placeholder,
        the two controls, the category names — follows the language the turn was
        written in, through `copy.py` like the rest of the chrome. This form used
        to be the one part of the UI that ignored that, hardcoding Spanish inside
        otherwise-English chrome with English category names beside it;
      * what Langfuse stores — the values in `REASON_ORDER` and the fallback
        comment — is frozen and never localised. A stored value that changed
        with the reader's language would split one category's history in two.
    """
    state = st.session_state.feedback.get(trace_id)
    if not (state and state.get("awaiting_detail")):
        return

    with st.container(key=f"pa-detail-{trace_id}"):
        st.caption(form_label(lang, "detail_prompt"))
        # {display label: stored value}, in the taxonomy's own order.
        choices = reason_choices(lang)
        label = st.selectbox(
            form_label(lang, "reason_label"),
            options=list(choices),
            key=f"reason_{trace_id}",
        )
        detail = st.text_area(
            form_label(lang, "detail_label"),
            key=f"detail_{trace_id}",
            placeholder=form_label(lang, "detail_placeholder"),
            height=80,
        )
        # A horizontal container, not `st.columns([1, 1, 6])`.
        #
        # The columns split the scroll area's 344px into ~40px each, which is
        # narrower than either label: the buttons rendered one letter per line,
        # in every language. Nobody had reported it because the form above them
        # was unreadable, so no tester ever got this far.
        #
        # This is how every other button row in the app is laid out —
        # `render_answer_actions`, `pa-chips`, `pa-reset` — and the pills hug
        # their own text, so it holds for a label of any length.
        with st.container(
            key=f"pa-detail-actions-{trace_id}",
            horizontal=True,
            vertical_alignment="center",
        ):
            if st.button(
                form_label(lang, "send"), key=f"send_{trace_id}", type="primary"
            ):
                reason = choices[label]
                comment = detail.strip() or f"({reason}) sin detalle"
                # Same score_id as the initial negative click -> upsert, not a duplicate.
                if submit_feedback(trace_id, 0, comment, reason=reason, turn_index=turn_index):
                    st.session_state.feedback[trace_id] = {
                        "value": 0,
                        "reason": reason,
                        "awaiting_detail": False,
                    }
                    st.toast(form_label(lang, "thanks_detail"))
                    st.rerun()

            if st.button(form_label(lang, "skip"), key=f"skip_{trace_id}"):
                # The value=0 score is already persisted; nothing to send.
                st.session_state.feedback[trace_id] = {
                    "value": 0,
                    "reason": None,
                    "awaiting_detail": False,
                }
                st.rerun()


def render_answer_actions(msg: ChatMessage) -> None:
    """
    The row under an assistant answer: two thumbs, then a "…" menu.

    Rendered from the history loop (NOT from inside the `chat_input` block), so
    it survives the rerun its own buttons trigger — the same constraint
    FRONTEND.md §11.9 records — and *outside* `st.chat_message`, so it sits
    under the card rather than inside it.

    The chosen thumb keeps the accent, which is how the row remembers a verdict
    without spending a sentence on it.
    """
    if not SHOW_PER_ANSWER_FEEDBACK:
        return
    trace_id = msg.get("trace_id")
    if not trace_id:
        return

    turn_index = msg.get("turn_index")
    lang = msg.get("language") or detect_language(msg.get("content", ""))
    state = st.session_state.feedback.get(trace_id)
    verdict = state.get("value") if state else None

    with st.container(
        key=f"pa-actions-{trace_id}",
        horizontal=True,
        vertical_alignment="center",
    ):
        if st.button(
            ":material/thumb_up:",
            key=f"good_{trace_id}",
            help=action_label(lang, "helpful"),
            type="primary" if verdict == 1 else "secondary",
        ):
            if verdict == 1:
                _clear_verdict(trace_id)
            else:
                _submit_and_store(trace_id, 1, turn_index, lang)
        if st.button(
            ":material/thumb_down:",
            key=f"bad_{trace_id}",
            help=action_label(lang, "not_helpful"),
            type="primary" if verdict == 0 else "secondary",
        ):
            if verdict == 0:
                _clear_verdict(trace_id)
            else:
                _submit_and_store(trace_id, 0, turn_index, lang)

        # st.popover, not a hand-rolled menu: its panel portals to the document
        # root and closes on outside-click for free. It holds one item today.
        # No `help=` on this one: the tooltip only restated the icon, and it
        # landed between the row and the menu it opens.
        with st.popover(":material/more_horiz:"):
            if st.button(
                action_label(lang, "view_sources"),
                icon=":material/description:",
                key=f"src_{trace_id}",
            ):
                open_now = st.session_state.sources_open.get(trace_id, False)
                st.session_state.sources_open[trace_id] = not open_now
                st.rerun()

    render_sources(msg, trace_id, lang)
    render_feedback_detail(trace_id, turn_index, lang)


# ==========================================
# UI: MAIN CHAT INTERFACE
# ==========================================
online = st.session_state.db_online

# Mode slider first: it sits in the top-right corner, above the title block.
theme_slider()

page_header(PAGE_TITLE, PAGE_SUBTITLE)

# ── The phone ─────────────────────────────────────────────────────────────
# Bezel -> screen -> scrollable chat area + inline composer. `screen_scroll` is
# captured so the live turn below can render into it after the composer has
# already been laid out inside the phone.
with st.container(key="pa-phone"):
    with st.container(key="pa-screen"):
        phone_header(
            PHONE_BRAND,
            "Online" if online else "Unavailable",
            online=online,
        )

        screen_scroll = st.container(height=SCREEN_HEIGHT_PX, key="pa-scroll")

        with screen_scroll:
            if not online:
                # Same guidance the page used to show as a full-width error,
                # now inside the screen so the shell stays intact.
                st.error(st.session_state.get("db_message", "Service unavailable."))

            # Chat history. Feedback rides on answers the assistant has
            # actually settled — see `is_definitive_answer`.
            for msg in st.session_state.messages:
                with st.chat_message(msg["role"]):
                    role_marker(msg["role"])
                    if msg["role"] == "assistant":
                        assistant_label()
                    st.markdown(msg["content"])
                    if msg["role"] == "assistant" and msg.get("debug"):
                        render_debug(msg["debug"])

                # Outside the card: the action row is *about* the answer, not
                # part of it, and the reference design puts it under the message.
                if msg["role"] == "assistant" and msg.get("can_rate"):
                    render_answer_actions(msg)

                # Openers again, under the action row on the newest answer.
                #
                # The newest one only: these are a live affordance, not
                # transcript content. Under every past answer they would be
                # three dead pills per turn, and a click from mid-conversation
                # would read as editing history rather than asking next.
                #
                # After the row, so the order under an answer is: what you can
                # say about it, then what you can ask next.
                if (
                    msg["role"] == "assistant"
                    and not msg.get("opening")
                    and msg is st.session_state.messages[-1]
                ):
                    next_chips = msg.get("suggestions") or []
                    if next_chips:
                        render_suggestions(
                            next_chips,
                            disabled=not online,
                            namespace="pa-chips-next",
                        )

                # Openers sit outside the greeting card, as in the prototypes,
                # and only while the greeting is still the whole conversation.
                if msg.get("opening") and is_opening_only(st.session_state.messages):
                    render_suggestions(SUGGESTIONS, disabled=not online)

        # Nested inside a container, so it renders inline in the phone rather
        # than pinned to the bottom of the viewport.
        prompt = st.chat_input(
            "Ask anything…" if online else "Unavailable — the knowledge graph is offline",
            disabled=not online,
        )

# A clicked opener behaves like a typed message. Popped unconditionally so a
# stale value can never fire a turn on a later rerun.
suggested = st.session_state.pop("pending_prompt", None)
if suggested and not prompt:
    prompt = suggested

page_footer(FOOTER_TEAM, FOOTER_PHASE)

# Reset stays available, kept quiet and off the phone.
with st.container(key="pa-reset", horizontal=True, horizontal_alignment="center"):
    if st.button("Reset conversation"):
        st.session_state.messages = initial_messages()
        st.session_state.thread_id = str(uuid.uuid4())
        st.session_state.feedback = {}
        st.session_state.turn_counter = 0
        st.rerun()

# ── Reading position ──────────────────────────────────────────────────────
# Last thing on the page, so the helper's iframe — collapsed to zero height by
# the stylesheet — lands outside the phone and cannot disturb its geometry.
#
# Streamlit leaves a height-constrained container scrolled to the bottom after a
# rerun, so a long answer arrived with its *end* on screen and the reader had to
# scroll back up to find their own question — the most-cited complaint in the
# user-testing sessions. This puts the question near the top instead, with the
# opening lines of the answer under it, and then stops: the conversation reads as
# a flow the user scrolls through, not a jump to the end.
#
# The token changes once per turn, so a mode toggle, a feedback click or any
# other rerun leaves the scroll position exactly where the reader put it.
if st.session_state.turn_counter > 0:
    scroll_to_question(
        token=f"{st.session_state.thread_id}:{st.session_state.turn_counter}"
    )


# `is_definitive_answer` — which decides whether an answer gets the feedback row
# — and `TurnProgress` — which decides what the wait shows — both live in
# `src/ui/turns.py` now. Neither touches Streamlit or the graph, so both are
# unit-tested in test/ui/test_turns.py; from here they are just called.
#
# The three stages the status lines report are the real shape of the graph —
# planner routing, orchestrator retrieval, synthesizer generation — not
# decoration (FRONTEND.md §8.2). That mapping is `TurnProgress`'s contract.


def render_status(slot, rows: list[tuple[str, bool]]) -> None:
    """
    Paint the growing status stack into `slot`.

    `rows` is the whole stack, repainted each time: an `st.empty()` holds one
    element, so advancing a stage means re-rendering the list, not appending to
    it. Into a container rather than straight into the placeholder — writing
    markdown into it directly leaves the previous block behind on some reruns.
    """
    with slot.container():
        status_stack(rows)


def run_turn(
    prompt: str,
    trace_id: str,
    turn_index: int,
    status_slot=None,
) -> tuple[str, bool, list[tuple[str, str]]]:
    """
    Executes the graph and reports progress into `status_slot`.
    Separated from the trace plumbing so the span wrapper stays readable.

    Returns the final response, whether it is a definitive answer, and the
    pipeline-debug lines (see `render_debug`).

    The status stack is `TurnProgress` (src/ui/turns.py); this function's job is
    to translate graph events into calls on it, collect the debug lines, and
    keep the trace plumbing out of both. The language it reports starts from
    `detect_language(prompt)` — the first line has to render before the graph is
    called, so there is nothing else to read yet — and switches to the planner's
    `detected_language` as soon as that arrives. Both are "es"/"en"
    (src/agent/nodes.py:231), so no mapping is needed.
    """
    config = {
        "configurable": {"thread_id": st.session_state.thread_id},
        "callbacks": [CallbackHandler()] if lf else [],
        # No langfuse_trace_id here: in v3 the handler takes trace identity from
        # the active OTel context (the span we open below), not from metadata.
        # These two are plain business metadata, useful when filtering.
        "metadata": {
            "thread_id": st.session_state.thread_id,
            "turn_index": turn_index,
        },
    }

    final_response = ""
    plan_steps: list = []
    suggestions: list[str] = []
    agent_runs: list[tuple[str, str | None]] = []
    debug_lines: list[tuple[str, str]] = []   # (kind, text), replayed below

    def paint(rows: list[tuple[str, bool]]) -> None:
        if status_slot is not None:
            render_status(status_slot, rows)

    # The status stack. Seeded with the guess from the prompt, because the first
    # line has to render before the graph is called and there is nothing else to
    # read yet; it adopts the planner's `detected_language` as soon as that
    # arrives. `paint` runs on each row that actually opens, and only then.
    progress = TurnProgress(detect_language(prompt), on_change=paint)

    # Something on screen before the graph is even called — the wait used to
    # start with nothing at all, which was the whole complaint.
    progress.begin()

    for event in graph.stream(
        {"messages": [HumanMessage(content=prompt)]},
        config=config,
        stream_mode="updates",
    ):
        if "planner" in event:
            plan = event["planner"].get("execution_plan", [])
            plan_steps = list(plan)
            progress.plan(plan_steps, event["planner"].get("detected_language"))

            debug_lines.append(("md", "**Planner Output:**"))
            for step in plan:
                debug_lines.append(
                    ("md", f"- Step {step.step} `[{step.assigned_agent}]`: {step.task}")
                )

        elif "orchestrator" in event:
            # One sub-agent per invocation, looping back to itself — so each
            # pass is a real unit of retrieval and earns the next line.
            progress.step_finished()

            orch_state = event.get("orchestrator")
            if isinstance(orch_state, dict):
                results = orch_state.get("agent_results", {})
                if results:
                    latest_key = sorted(results.keys())[-1]
                    latest_res = results[latest_key]

                    agent_name = getattr(latest_res, "agent", "unknown")
                    error_msg = getattr(latest_res, "error", None)
                    agent_runs.append((agent_name, error_msg))

                    if error_msg:
                        debug_lines.append(
                            ("error", f"**{agent_name.upper()} Agent Error:** {error_msg}")
                        )
                    else:
                        debug_lines.append(
                            ("info", f"**{agent_name.upper()} Agent executed successfully.**")
                        )

        elif "synthesizer" in event:
            # Covers the plan-less case; a no-op when the branch above already
            # opened the generation row.
            progress.generating()
            messages = event["synthesizer"].get("messages", [])
            if messages:
                final_response = messages[-1].content
        elif "suggester" in event:
            # El nodo SIEMPRE escribe la clave, aunque sea con []. Sin esta
            # rama el evento caía al vacío y los chips del grafo no salían
            # nunca de run_turn — los que se veían eran el deck estático.
            suggestions = _chip_texts(event["suggester"].get("suggestions"))
    return (
        final_response,
        is_definitive_answer(plan_steps, agent_runs, final_response),
        debug_lines,
        suggestions,
    )


# User Input — the composer lives inside the phone, above.
# Rendering through `screen_scroll` keeps the live turn inside the phone's
# scroll area, which was laid out before the composer.
if prompt:
    # Monotonic turn index -> the seed is unique even if a previous turn failed.
    st.session_state.turn_counter += 1
    turn_index = st.session_state.turn_counter

    # Deterministic, OTEL-compatible trace id (32 lowercase hex chars).
    current_trace_id = Langfuse.create_trace_id(
        seed=f"{st.session_state.thread_id}:{turn_index}"
    )

    question: ChatMessage = {"role": "user", "content": prompt}
    st.session_state.messages.append(question)
    with screen_scroll.chat_message("user"):
        role_marker("user")
        st.markdown(prompt)

    # The wait, rendered honestly.
    #
    # A plain placeholder rather than `st.status`: that widget draws its own
    # expander chrome and its label ("Agent Thinking Process...") was developer
    # language sitting where an answer belongs.
    #
    # It also sits *outside* `chat_message`, on the bare screen surface, exactly
    # as `.status` does in demo-deep-water.html — the assistant's glass card and
    # its "Your assistant" label only appear once there is something to put in
    # them. Opening the card first promised content that did not exist yet.
    status_slot = screen_scroll.empty()

    final_response = ""
    definitive = False
    debug_lines: list[tuple[str, str]] = []
    suggestions: list[str] = []
    turn_error: Exception | None = None

    if lf is not None:

        with lf.start_as_current_observation(
            as_type="span",
            name=TRACE_NAME,
            trace_context={"trace_id": current_trace_id},
            input={"prompt": prompt},
        ) as span:

            propagate_attributes(
                user_id=st.session_state.thread_id,
                session_id=st.session_state.thread_id,
                tags=["streamlit", "pool-chemistry"],
                metadata={
                    "turn_index": turn_index,
                },
            )

            try:
                final_response, definitive, debug_lines = run_turn(
                    prompt,
                    current_trace_id,
                    turn_index,
                    status_slot=status_slot,
                )

                span.update(
                    output={"response": final_response}
                )

                span.set_trace_io(
                    input={"prompt": prompt},
                    output={"response": final_response},
                )

            except Exception as e:
                turn_error = e

                span.update(
                    level="ERROR",
                    status_message=str(e),
                    output={"error": str(e)},
                )

                span.set_trace_io(
                    input={"prompt": prompt},
                    output={"error": str(e)},
                )

        lf.flush()
    else:
        try:
            final_response, definitive, debug_lines = run_turn(
                prompt, current_trace_id, turn_index,
                status_slot=status_slot,
            )
        except Exception as e:
            turn_error = e

    # Clear the status either way. On the failure path this used to be
    # left mid-flight, so the last thing on screen was a half-finished
    # progress widget above an error.
    status_slot.empty()

    if turn_error is not None:
        # Into the screen, not the page: the guidance belongs inside the phone,
        # the same reasoning as the offline notice above.
        screen_scroll.error(f"El agente falló: {turn_error}")
        st.stop()

    if final_response:
        # Now the card: label and answer together, as one object arriving.
        with screen_scroll.chat_message("assistant"):
            role_marker("assistant")
            assistant_label()
            # Written out rather than pasted in, on the demo's cadence
            # (theme.py::type_out). Presentation only: the text is already
            # complete here, so nothing about the reveal claims the tokens are
            # arriving live. The history loop above renders the same answer
            # instantly on every later rerun — a turn is typed once.
            type_out(st.empty(), final_response)
            render_debug(debug_lines)

        # trace_id + turn_index travel with the message so any past turn
        # stays scorable and its score keeps its conversation coordinates.
        # `can_rate` is decided once, here: a turn cannot become rateable
        # later, and re-deriving it on every rerun would be guesswork from
        # the text alone. Field-by-field documentation is on `ChatMessage`.
        answer: ChatMessage = {
            "role": "assistant",
            "content": final_response,
            "trace_id": current_trace_id,
            "turn_index": turn_index,
            "can_rate": definitive,
            # The chrome under the answer follows the language the reader
            # wrote in, so it is settled once here rather than re-detected
            # from the answer text on every rerun.
            "language": detect_language(prompt),
            # Nothing populates AgentResult.sources yet (FRONTEND.md §15), so
            # this is an empty list today and the panel says so plainly. It is
            # the slot the backend fills when it starts returning them —
            # reading it here changes nothing on that side.
            "sources": [],
            # Only kept when the flag is on: off, this is dead weight in session
            # state for every turn of the conversation.
            "debug": debug_lines if SHOW_PIPELINE_DEBUG else None,
            "suggestions": suggestions,
        }
        st.session_state.messages.append(answer)
        # Rerun so the feedback widget renders from the history loop, where
        # it survives the reruns that its own buttons trigger.
        st.rerun()